import { FieldPath, FieldValue, Timestamp, getFirestore, type Firestore } from 'firebase-admin/firestore'
import { HttpsError } from 'firebase-functions/v2/https'
import { requireBusinessRole, type AuthContext } from './businessAccess.js'
import { businessDateKey, daysUntilExpiry, expiryState, suggestedExpiryDiscount } from './expiryDomain.js'
import { allocateFefo, validateReceiveStock, validateStockCount, validateWriteOff, type FefoBatch } from './inventoryDomain.js'
import { DEFAULT_OPERATIONS_SETTINGS, normalizeOperationsSettings } from './operationsSettings.js'
import { derivePromotionStatus, validatePromotionInput } from './promotionDomain.js'

const fail = (error: unknown) => { if (error instanceof HttpsError) throw error; throw new HttpsError('invalid-argument', error instanceof Error ? error.message : 'The request is invalid.') }
const movementType = (reason: string) => reason === 'expired' ? 'expiry_write_off' : reason === 'damaged' ? 'damaged_write_off' : reason === 'stock_count_correction' ? 'stock_count' : 'waste'

export async function receiveStockForRequest(data: unknown, auth: AuthContext | undefined, db: Firestore = getFirestore(), now = Timestamp.now()) {
  let input; try { input=validateReceiveStock(data) } catch(error){ return fail(error) }
  const caller=await requireBusinessRole(auth,['owner','manager','supervisor'],db,now)
  if(caller.role==='supervisor'&&input.costPrice!==undefined) throw new HttpsError('permission-denied','Supervisors cannot enter or view cost prices.')
  const productRef=caller.businessRef.collection('products').doc(input.productId); const batchRef=caller.businessRef.collection('inventoryBatches').doc(); const movementRef=caller.businessRef.collection('inventoryMovements').doc()
  return db.runTransaction(async transaction=>{
    const productSnapshot=await transaction.get(productRef); if(!productSnapshot.exists) throw new HttpsError('not-found','Product was not found.'); const product=productSnapshot.data()!
    if(product.status!=='active'||product.trackStock!==true) throw new HttpsError('failed-precondition','Choose an active stock-tracked product.')
    if(product.tracksExpiry===true&&!input.expiryDate) throw new HttpsError('invalid-argument','An expiry date is required for this product.')
    if(input.expiryDate&&daysUntilExpiry(input.expiryDate,businessDateKey(now.toDate()))<0) throw new HttpsError('invalid-argument','Expired stock cannot be received as active inventory.')
    let supplierNameSnapshot:string|null=null
    if(input.supplierId){const supplier=await transaction.get(caller.businessRef.collection('suppliers').doc(input.supplierId));if(!supplier.exists||supplier.data()?.status!=='active')throw new HttpsError('invalid-argument','Choose an active supplier.');supplierNameSnapshot=String(supplier.data()?.name??'')}
    const before=Number(product.quantity??0),after=before+input.quantity,cost=caller.role==='supervisor'?Number(product.costPrice??0):input.costPrice??Number(product.costPrice??0)
    transaction.update(productRef,{quantity:after,lastMovementId:movementRef.id,updatedAt:now})
    transaction.create(batchRef,{batchId:batchRef.id,productId:productSnapshot.id,productNameSnapshot:String(product.name??''),categorySnapshot:String(product.category??''),expiryWarningDays:Number.isInteger(product.expiryWarningDays)?product.expiryWarningDays:null,expiryCriticalDays:Number.isInteger(product.expiryCriticalDays)?product.expiryCriticalDays:null,quantityReceived:input.quantity,quantityRemaining:input.quantity,receivedAt:now,expiryDate:input.expiryDate,supplierId:input.supplierId,supplierNameSnapshot,reference:input.reference,costPriceSnapshot:cost,status:'active',createdBy:caller.uid,createdByNameSnapshot:caller.displayName,createdAt:now,updatedAt:now})
    transaction.create(movementRef,{productId:productSnapshot.id,productName:String(product.name??''),type:'receiving',quantityChange:input.quantity,quantityBefore:before,quantityAfter:after,reason:'Stock received',notes:'',referenceId:input.reference||null,batchId:batchRef.id,batchAllocations:[{batchId:batchRef.id,quantity:input.quantity}],staffNameSnapshot:caller.displayName,createdAt:now,createdBy:caller.uid})
    transaction.create(caller.businessRef.collection('staffActivity').doc(),{type:'stock_received',actorUid:caller.uid,targetUid:caller.uid,actorName:caller.displayName,targetName:String(product.name??''),description:`${caller.displayName} received ${input.quantity} units of ${product.name}.`,batchId:batchRef.id,createdAt:now})
    return {batchId:batchRef.id,quantityAfter:after}
  })
}

async function queryProductBatches(transaction: FirebaseFirestore.Transaction, caller: Awaited<ReturnType<typeof requireBusinessRole>>, productId:string) {
  const snapshot=await transaction.get(caller.businessRef.collection('inventoryBatches').where('productId','==',productId).where('status','==','active').orderBy('expiryDate').orderBy(FieldPath.documentId()).limit(200))
  return snapshot.docs.map(doc=>({id:doc.id,...doc.data()} as FefoBatch & FirebaseFirestore.DocumentData))
}

export async function writeOffStockForRequest(data: unknown, auth: AuthContext|undefined, db:Firestore=getFirestore(), now=Timestamp.now()){
  let input;try{input=validateWriteOff(data)}catch(error){return fail(error)} const caller=await requireBusinessRole(auth,['owner','manager','supervisor'],db,now)
  const productRef=caller.businessRef.collection('products').doc(input.productId),movementRef=caller.businessRef.collection('inventoryMovements').doc()
  return db.runTransaction(async transaction=>{const snap=await transaction.get(productRef);if(!snap.exists)throw new HttpsError('not-found','Product was not found.');const product=snap.data()!,before=Number(product.quantity??0);if(before<input.quantity)throw new HttpsError('failed-precondition',`Only ${before} units are recorded.`)
    const allocations:Array<{batchId:string;quantity:number}>=[]
    if(product.tracksExpiry===true){if(!input.batchId)throw new HttpsError('invalid-argument','Choose the batch to write off.');const batchRef=caller.businessRef.collection('inventoryBatches').doc(input.batchId);const batch=await transaction.get(batchRef);if(!batch.exists||batch.data()?.productId!==snap.id)throw new HttpsError('invalid-argument','The batch does not belong to this product.');const remaining=Number(batch.data()?.quantityRemaining??0);if(batch.data()?.status!=='active'||remaining<input.quantity)throw new HttpsError('failed-precondition',`Only ${remaining} units remain in that active batch.`);const batchAfter=remaining-input.quantity;transaction.update(batchRef,{quantityRemaining:batchAfter,status:batchAfter===0?(input.reason==='expired'?'expired':'depleted'):'active',updatedAt:now});allocations.push({batchId:batch.id,quantity:input.quantity})}
    const after=before-input.quantity;transaction.update(productRef,{quantity:after,lastMovementId:movementRef.id,updatedAt:now});transaction.create(movementRef,{productId:snap.id,productName:String(product.name??''),type:movementType(input.reason),quantityChange:-input.quantity,quantityBefore:before,quantityAfter:after,reason:input.reason.replace(/_/g,' '),notes:input.notes,referenceId:null,batchId:input.batchId,batchAllocations:allocations,staffNameSnapshot:caller.displayName,createdAt:now,createdBy:caller.uid});transaction.create(caller.businessRef.collection('staffActivity').doc(),{type:'stock_written_off',actorUid:caller.uid,targetUid:caller.uid,actorName:caller.displayName,targetName:String(product.name??''),description:`${caller.displayName} wrote off ${input.quantity} units of ${product.name} (${input.reason.replace(/_/g,' ')}).`,batchId:input.batchId,createdAt:now});return{quantityAfter:after}})
}

export async function performStockCountForRequest(data:unknown,auth:AuthContext|undefined,db:Firestore=getFirestore(),now=Timestamp.now()){
  let input;try{input=validateStockCount(data)}catch(error){return fail(error)} const caller=await requireBusinessRole(auth,['owner','manager','supervisor'],db,now);const productRef=caller.businessRef.collection('products').doc(input.productId),movementRef=caller.businessRef.collection('inventoryMovements').doc()
  return db.runTransaction(async transaction=>{const snap=await transaction.get(productRef);if(!snap.exists)throw new HttpsError('not-found','Product was not found.');const product=snap.data()!,before=Number(product.quantity??0),variance=input.countedQuantity-before;if(!variance)return{quantityAfter:before,variance:0};const allocations:Array<{batchId:string;quantity:number}>=[]
    if(product.tracksExpiry===true){if(variance>0)throw new HttpsError('failed-precondition','Receive unrecorded expiry-tracked stock as a batch before completing this count.');const batches=await queryProductBatches(transaction,caller,snap.id);let fefo;try{fefo=allocateFefo(batches,-variance,businessDateKey(now.toDate()))}catch(error){return fail(error)};for(const allocation of fefo){const ref=caller.businessRef.collection('inventoryBatches').doc(allocation.batchId);transaction.update(ref,{quantityRemaining:allocation.quantityAfter,status:allocation.quantityAfter===0?'depleted':'active',updatedAt:now});allocations.push({batchId:allocation.batchId,quantity:allocation.quantity})}}
    transaction.update(productRef,{quantity:input.countedQuantity,lastMovementId:movementRef.id,updatedAt:now});transaction.create(movementRef,{productId:snap.id,productName:String(product.name??''),type:'stock_count',quantityChange:variance,quantityBefore:before,quantityAfter:input.countedQuantity,reason:input.reason,notes:input.notes,referenceId:null,batchId:null,batchAllocations:allocations,staffNameSnapshot:caller.displayName,createdAt:now,createdBy:caller.uid});transaction.create(caller.businessRef.collection('staffActivity').doc(),{type:'stock_count_completed',actorUid:caller.uid,targetUid:caller.uid,actorName:caller.displayName,targetName:String(product.name??''),description:`${caller.displayName} counted ${product.name}: ${before} to ${input.countedQuantity} (${variance>0?'+':''}${variance}).`,createdAt:now});return{quantityAfter:input.countedQuantity,variance}})
}

export async function listExpiryBatchesForRequest(data:unknown,auth:AuthContext|undefined,db:Firestore=getFirestore(),now=Timestamp.now()){
  if(!data||typeof data!=='object'||Array.isArray(data))throw new HttpsError('invalid-argument','A page request is required.');const v=data as Record<string,unknown>;if(Object.keys(v).some(k=>!['cursorExpiryDate','cursorId','pageSize'].includes(k)))throw new HttpsError('invalid-argument','Unsupported expiry filter.')
  const caller=await requireBusinessRole(auth,['owner','manager','supervisor'],db,now);const size=Number.isInteger(v.pageSize)&&Number(v.pageSize)>0&&Number(v.pageSize)<=100?Number(v.pageSize):40;let query:FirebaseFirestore.Query=caller.businessRef.collection('inventoryBatches').where('expiryDate','>=','0000-01-01').orderBy('expiryDate').orderBy(FieldPath.documentId());if(typeof v.cursorExpiryDate==='string'&&typeof v.cursorId==='string')query=query.startAfter(v.cursorExpiryDate,v.cursorId);const snapshot=await query.limit(size+1).get();const settingsSnap=await caller.businessRef.collection('settings').doc('operations').get();const settings=normalizeOperationsSettings(settingsSnap.data());const today=businessDateKey(now.toDate());const financial=caller.role==='owner'||caller.role==='manager';const docs=snapshot.docs.slice(0,size)
  return{items:docs.map(doc=>{const batch=doc.data(),warning=Number(batch.expiryWarningDays??settings.defaultExpiryWarningDays),critical=Number(batch.expiryCriticalDays??settings.defaultExpiryCriticalDays),state=expiryState(batch.expiryDate,warning,critical,today),suggestion=settings.expiryDiscountEnabled?suggestedExpiryDiscount(batch.expiryDate,settings.expiryDiscountRules,today):null;const result:Record<string,unknown>={id:doc.id,batchId:doc.id,productId:batch.productId,productNameSnapshot:batch.productNameSnapshot,categorySnapshot:batch.categorySnapshot??'',quantityReceived:batch.quantityReceived,quantityRemaining:batch.quantityRemaining,receivedAt:batch.receivedAt?.toMillis?.()??null,expiryDate:batch.expiryDate,supplierId:batch.supplierId,supplierNameSnapshot:batch.supplierNameSnapshot,reference:batch.reference,status:state==='expired'?'expired':batch.status,createdBy:batch.createdBy,createdByNameSnapshot:batch.createdByNameSnapshot,createdAt:batch.createdAt?.toMillis?.()??null,updatedAt:batch.updatedAt?.toMillis?.()??null,expiryState:state,daysRemaining:daysUntilExpiry(batch.expiryDate,today),suggestedDiscount:suggestion};if(financial){result.costPriceSnapshot=batch.costPriceSnapshot;result.estimatedValueAtRisk=Math.round(Number(batch.costPriceSnapshot??0)*Number(batch.quantityRemaining??0)*100)/100}return result}),cursor:docs.length?{expiryDate:docs.at(-1)!.data().expiryDate,id:docs.at(-1)!.id}:null,hasMore:snapshot.size>size,financialValuesIncluded:financial}
}

export async function getExpirySummaryForRequest(_data:unknown,auth:AuthContext|undefined,db:Firestore=getFirestore(),now=Timestamp.now()){
  if(!_data||typeof _data!=='object'||Array.isArray(_data)||Object.keys(_data as object).length)throw new HttpsError('invalid-argument','This request does not accept fields.');const caller=await requireBusinessRole(auth,['owner','manager','supervisor'],db,now);const settings=normalizeOperationsSettings((await caller.businessRef.collection('settings').doc('operations').get()).data());if(!settings.expiryAlertsEnabled)return{enabled:false,unitsAtRisk:0,expiresTodayUnits:0,expiredBatches:0};const today=businessDateKey(now.toDate());const horizon=new Date(now.toMillis()+settings.defaultExpiryWarningDays*86400000).toISOString().slice(0,10);const snapshot=await caller.businessRef.collection('inventoryBatches').where('expiryDate','>=','0000-01-01').where('expiryDate','<=',horizon).orderBy('expiryDate').limit(500).get();let unitsAtRisk=0,expiresTodayUnits=0,expiredBatches=0,value=0;for(const doc of snapshot.docs){const b=doc.data(),qty=Number(b.quantityRemaining??0);if(!qty||!['active','expired'].includes(b.status))continue;unitsAtRisk+=qty;if(b.expiryDate===today)expiresTodayUnits+=qty;if(b.expiryDate<today)expiredBatches++;value+=qty*Number(b.costPriceSnapshot??0)}const result:Record<string,unknown>={enabled:true,unitsAtRisk,expiresTodayUnits,expiredBatches};if(caller.role==='owner'||caller.role==='manager')result.estimatedValueAtRisk=Math.round(value*100)/100;return result}

export async function savePromotionForRequest(data:unknown,auth:AuthContext|undefined,db:Firestore=getFirestore(),now=Timestamp.now()){
  let input;try{input=validatePromotionInput(data)}catch(error){return fail(error)}const caller=await requireBusinessRole(auth,['owner','manager'],db,now);const raw=data as Record<string,unknown>;const promotionId=typeof raw.id==='string'&&/^[A-Za-z0-9_-]{1,150}$/.test(raw.id)?raw.id:null;const ref=promotionId?caller.businessRef.collection('promotions').doc(promotionId):caller.businessRef.collection('promotions').doc();if(input.productId){const p=await caller.businessRef.collection('products').doc(input.productId).get();if(!p.exists)throw new HttpsError('invalid-argument','Promotion product was not found.')}const existing=promotionId?await ref.get():null;const status=derivePromotionStatus(input.status,input.startsAt,input.endsAt,now.toMillis());await ref.set({...input,status,startsAt:Timestamp.fromMillis(input.startsAt),endsAt:Timestamp.fromMillis(input.endsAt),createdBy:existing?.data()?.createdBy??caller.uid,createdAt:existing?.data()?.createdAt??now,updatedAt:now},{merge:false});await caller.businessRef.collection('staffActivity').add({type:promotionId?'promotion_updated':'promotion_created',actorUid:caller.uid,targetUid:caller.uid,actorName:caller.displayName,targetName:input.name,description:`${caller.displayName} ${promotionId?'updated':'created'} promotion ${input.name}.`,createdAt:now});return{id:ref.id,status}
}
export async function listPromotionsForRequest(data:unknown,auth:AuthContext|undefined,db:Firestore=getFirestore(),now=Timestamp.now()){
  if(!data||typeof data!=='object'||Array.isArray(data)||Object.keys(data as object).some(k=>!['cursorUpdatedAt','cursorId','pageSize'].includes(k)))throw new HttpsError('invalid-argument','Invalid promotion page.');const v=data as Record<string,unknown>,caller=await requireBusinessRole(auth,['owner','manager','supervisor','cashier'],db,now);const size=Number.isInteger(v.pageSize)&&Number(v.pageSize)>0&&Number(v.pageSize)<=100?Number(v.pageSize):40;let query:FirebaseFirestore.Query=caller.businessRef.collection('promotions').orderBy('updatedAt','desc').orderBy(FieldPath.documentId(),'desc');if(Number.isFinite(v.cursorUpdatedAt)&&typeof v.cursorId==='string')query=query.startAfter(Timestamp.fromMillis(Number(v.cursorUpdatedAt)),v.cursorId);const snapshot=await query.limit(size+1).get(),docs=snapshot.docs.slice(0,size);return{items:docs.map(doc=>{const p=doc.data();return{id:doc.id,...p,startsAt:p.startsAt?.toMillis?.()??0,endsAt:p.endsAt?.toMillis?.()??0,createdAt:p.createdAt?.toMillis?.()??null,updatedAt:p.updatedAt?.toMillis?.()??null,status:derivePromotionStatus(p.status,p.startsAt?.toMillis?.()??0,p.endsAt?.toMillis?.()??0,now.toMillis())}}),cursor:docs.length?{updatedAt:docs.at(-1)!.data().updatedAt?.toMillis?.()??0,id:docs.at(-1)!.id}:null,hasMore:snapshot.size>size}
}
export async function setPromotionStatusForRequest(data:unknown,auth:AuthContext|undefined,db:Firestore=getFirestore(),now=Timestamp.now()){
  if(!data||typeof data!=='object'||Array.isArray(data))throw new HttpsError('invalid-argument','Promotion status is required.');const v=data as Record<string,unknown>;if(Object.keys(v).some(k=>!['id','status'].includes(k))||typeof v.id!=='string'||!/^[A-Za-z0-9_-]{1,150}$/.test(v.id)||!['draft','active','disabled'].includes(String(v.status)))throw new HttpsError('invalid-argument','Choose a valid promotion status.');const caller=await requireBusinessRole(auth,['owner','manager'],db,now),ref=caller.businessRef.collection('promotions').doc(v.id),snapshot=await ref.get();if(!snapshot.exists)throw new HttpsError('not-found','Promotion was not found.');await ref.update({status:v.status,updatedAt:now});await caller.businessRef.collection('staffActivity').add({type:'promotion_status_changed',actorUid:caller.uid,targetUid:caller.uid,actorName:caller.displayName,targetName:snapshot.data()?.name??'Promotion',description:`${caller.displayName} changed promotion ${snapshot.data()?.name??''} to ${v.status}.`,createdAt:now});return{ok:true}
}
