import { expect, test } from '@playwright/test'
import { Timestamp } from 'firebase-admin/firestore'
import { adminAuth, adminDb, login, PASSWORD, resetEmulators, seedBusiness, seedUser } from './support/emulator'

test.beforeEach(async ({ request }) => resetEmulators(request))

test('staff invitation is local-only, accepted with the correct role, then suspended, reactivated and disabled', async ({ page }) => {
  test.setTimeout(120_000)
  const businessId = await seedBusiness('Invitation Test Business')
  const owner = await seedUser(businessId, 'owner')
  const invitedEmail = `invited-${Date.now()}@example.test`
  await login(page, owner.email)
  await page.getByRole('link', { name: 'Staff' }).click()
  await page.getByRole('button', { name: 'Add staff' }).click()
  await page.getByLabel(/Name/).fill('Invited Cashier')
  await page.getByLabel(/Email/).fill(invitedEmail)
  await page.getByLabel(/Role/).selectOption('cashier')
  const responsePromise = page.waitForResponse((response) => response.url().includes('/inviteStaff') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Create invitation' }).click()
  const payload = await (await responsePromise).json() as { result: { testingInvitationUrl?: string; testingPasswordSetupUrl?: string } }
  expect(payload.result.testingInvitationUrl).toContain('/staff-invitation?token=')
  expect(payload.result.testingPasswordSetupUrl).toBeTruthy()
  await expect(page.getByText('Local invitation created. No email was sent.')).toBeVisible()
  await expect(page.getByText('Invitation email sent.')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Copy invitation link' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copy password setup link' })).toBeVisible()

  const invitation = await adminDb.collection(`businesses/${businessId}/staffInvitations`).where('invitedEmail', '==', invitedEmail).limit(1).get()
  expect(invitation.size).toBe(1)
  expect(invitation.docs[0].data()).toMatchObject({ proposedRole: 'cashier', status: 'sent', providerMessageId: 'emulator-no-email' })
  await invitation.docs[0].ref.update({ lastDeliveryAt: Timestamp.fromMillis(1) })

  const resendResponsePromise = page.waitForResponse((response) => response.url().includes('/resendStaffInvite') && response.request().method() === 'POST')
  await page.getByRole('row').filter({ hasText: invitedEmail }).getByRole('button', { name: 'Resend' }).click()
  const resendPayload = await (await resendResponsePromise).json() as { result: { testingInvitationUrl?: string; testingPasswordSetupUrl?: string } }
  expect(resendPayload.result.testingInvitationUrl).toContain('/staff-invitation?token=')
  expect(resendPayload.result.testingInvitationUrl).not.toBe(payload.result.testingInvitationUrl)
  expect(resendPayload.result.testingPasswordSetupUrl).toBeTruthy()
  await expect(page.getByText(/previous invitation link is invalid/i)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copy invitation link' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copy password setup link' })).toBeVisible()

  const invitedUser = await adminAuth.getUserByEmail(invitedEmail)
  await adminAuth.updateUser(invitedUser.uid, { password: PASSWORD })

  await page.getByRole('button', { name: 'Sign out' }).click()
  const inviteUrl = new URL(resendPayload.result.testingInvitationUrl!)
  await page.goto(`${inviteUrl.pathname}${inviteUrl.search}`)
  await page.getByRole('link', { name: 'Sign in to continue' }).click()
  await page.getByLabel('Email').fill(invitedEmail)
  await page.getByLabel('Password').fill(PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const acceptResponse = page.waitForResponse((response) => response.url().includes('/acceptStaffInvitation') && response.request().method() === 'POST', { timeout: 30_000 })
  await page.getByRole('button', { name: 'Accept invitation' }).click()
  expect((await acceptResponse).ok()).toBe(true)
  await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible({ timeout: 30_000 })
  await expect(page.getByText('cashier', { exact: true })).toBeVisible()
  expect((await adminDb.doc(`businesses/${businessId}/members/${invitedUser.uid}`).get()).data()).toMatchObject({ role: 'cashier', status: 'active' })

  await page.getByRole('button', { name: 'Sign out' }).click()
  await login(page, owner.email)
  await page.goto('/staff')
  const row = page.getByRole('row').filter({ hasText: invitedEmail })
  const suspendResponse = page.waitForResponse((response) => response.url().includes('/updateStaffStatus') && response.request().method() === 'POST', { timeout: 30_000 })
  await row.getByRole('button', { name: 'Suspend' }).click()
  expect((await suspendResponse).ok()).toBe(true)
  await expect(row.getByText('suspended', { exact: true })).toBeVisible()
  const reactivateResponse = page.waitForResponse((response) => response.url().includes('/updateStaffStatus') && response.request().method() === 'POST', { timeout: 30_000 })
  await row.getByRole('button', { name: 'Reactivate' }).click()
  expect((await reactivateResponse).ok()).toBe(true)
  await expect(row.getByText('active', { exact: true })).toBeVisible()
  const disableResponse = page.waitForResponse((response) => response.url().includes('/updateStaffStatus') && response.request().method() === 'POST', { timeout: 30_000 })
  await row.getByRole('button', { name: 'Disable' }).click()
  expect((await disableResponse).ok()).toBe(true)
  await expect(row.getByText('disabled', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.goto('/login')
  await page.getByLabel('Email').fill(invitedEmail)
  await page.getByLabel('Password').fill(PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('This sign-in has been disabled. Contact support.')
  await expect(page).toHaveURL(/\/login$/)
})
